# Generated by Django 4.0.6 on 2022-07-13 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sides_alter_step_step'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sides',
            new_name='Side',
        ),
    ]
