# Generated by Django 4.0.6 on 2022-07-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_sides_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='sides',
            field=models.ManyToManyField(to='main_app.side'),
        ),
    ]
